name: github-actions
on: 
  push: 
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  pipline:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '17'
      - run: npm install
        name: build production project
      - run: npm run build:prod
        name: linting typescript
      - run: npm run lint:ts
        name: linting css
      - run: npm run lint:scss
        name: unit testing
      - run: npm run test:unit
